/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author yassine
 */
public class HomePage extends javax.swing.JPanel {

    /**
     * Creates new form HomePAge
     */
    public HomePage() {
        initComponents();
    }
    public javax.swing.JButton getPfeBtn(){
        return pfeBtn;
    }
    public javax.swing.JButton getJuryBtn(){
        return juryBtn;
    }
    public javax.swing.JButton getEtudiantBtn(){
        return etudiantBtn;
    }
    public javax.swing.JButton getEnseignantBtn(){
        return enseignantBtn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        contentCenter = new javax.swing.JPanel();
        PFEPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pfeBtn = new javax.swing.JButton();
        JuryPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        juryBtn = new javax.swing.JButton();
        EtudiantPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        etudiantBtn = new javax.swing.JButton();
        EnseignantPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        enseignantBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        contentCenter.setBackground(java.awt.Color.white);
        contentCenter.setLayout(new javax.swing.BoxLayout(contentCenter, javax.swing.BoxLayout.Y_AXIS));

        PFEPanel.setOpaque(false);
        PFEPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel1.setText("Consulter la rebrique des PFEs  ");
        PFEPanel.add(jLabel1);

        pfeBtn.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        pfeBtn.setText("Consulter PFE");
        pfeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfeBtnActionPerformed(evt);
            }
        });
        PFEPanel.add(pfeBtn);

        contentCenter.add(PFEPanel);

        JuryPanel.setBackground(java.awt.Color.black);
        JuryPanel.setOpaque(false);
        JuryPanel.setPreferredSize(new java.awt.Dimension(491, 0));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel2.setText("Consulter la rebrique des Jurys  ");
        JuryPanel.add(jLabel2);

        juryBtn.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        juryBtn.setText("Consulter Jury");
        juryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juryBtnActionPerformed(evt);
            }
        });
        JuryPanel.add(juryBtn);

        contentCenter.add(JuryPanel);

        EtudiantPanel.setBackground(java.awt.Color.cyan);
        EtudiantPanel.setOpaque(false);
        EtudiantPanel.setPreferredSize(new java.awt.Dimension(538, 0));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel3.setText("Consulter la rebrique des Etudiant  ");
        EtudiantPanel.add(jLabel3);

        etudiantBtn.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        etudiantBtn.setText("Consulter Etudiant");
        etudiantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantBtnActionPerformed(evt);
            }
        });
        EtudiantPanel.add(etudiantBtn);

        contentCenter.add(EtudiantPanel);

        EnseignantPanel.setOpaque(false);
        EnseignantPanel.setPreferredSize(new java.awt.Dimension(631, 0));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel4.setText("Consulter la rebrique des Enseignant  ");
        EnseignantPanel.add(jLabel4);

        enseignantBtn.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        enseignantBtn.setText("Consulter Enseignant");
        enseignantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enseignantBtnActionPerformed(evt);
            }
        });
        EnseignantPanel.add(enseignantBtn);

        contentCenter.add(EnseignantPanel);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(1088, 300));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        contentCenter.add(jPanel2);

        add(contentCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void pfeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfeBtnActionPerformed

    private void juryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juryBtnActionPerformed

    private void etudiantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etudiantBtnActionPerformed

    private void enseignantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enseignantBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enseignantBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnseignantPanel;
    private javax.swing.JPanel EtudiantPanel;
    private javax.swing.JPanel JuryPanel;
    private javax.swing.JPanel PFEPanel;
    private javax.swing.JPanel contentCenter;
    private javax.swing.JButton enseignantBtn;
    private javax.swing.JButton etudiantBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton juryBtn;
    private javax.swing.JButton pfeBtn;
    // End of variables declaration//GEN-END:variables
}
