/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author yassine
 */
public class LoginCover extends javax.swing.JPanel {
    Image logoImg = new ImageIcon("./assets/logo.png").getImage().getScaledInstance(526,524, Image.SCALE_DEFAULT);
    int logoHeight= logoImg.getHeight(null);
    int logoWidth= logoImg.getWidth(null);
    /**
     * Creates new form LoginCover
     */
    public LoginCover() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;
        GradientPaint gra = new GradientPaint(0,0,Color.decode("#2c67f2"),0,getHeight(), Color.decode("#62cff4"));
        g2d.setPaint(gra);
        g2d.fillRect(0,0,getWidth(),getHeight());
        g2d.drawImage(logoImg, getWidth()/2 - 263,getHeight()/2 -290, null);
        super.paintComponent(g);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
