/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.miginfocom.swing.MigLayout;
import ui.Components.MyButton;
import ui.Components.MyPasswordField;
import ui.Components.MyTextField;


/**
 *
 * @author yassine
 */
public class LoginPanel extends javax.swing.JLayeredPane {
    MyButton submitBtn;
    private JPanel buttonPanel = new JPanel(new FlowLayout());
    public LoginPanel() {
        initComponents();
        init();
    }
    public void init(){
        login.setLayout(new MigLayout("wrap","push[center]push", "push[]25[]10[]25[]10[]60[]push"));
        MyLbl lbl = new MyLbl("Connexion",40,1);
        login.add(lbl);
        
        MyLbl usrLbl = new MyLbl("Username",34,0);
        login.add(usrLbl, "align left");
        MyTextField usrField = new MyTextField();
        login.add(usrField, "w 500");
        usrField.setFont(new  Font("sansserif",0,34));
        
        MyLbl passLbl = new MyLbl("Password",34,0);
        login.add(passLbl, "align left");
        MyPasswordField passField = new MyPasswordField();
        passField.setFont(new  Font("sansserif",10,34));
        login.add(passField, "w 500");
        
        submitBtn = new MyButton("S'authentifier", new Color(44, 103, 242), new Color(255, 255, 255));
        submitBtn.setFont(new  Font("sansserif",0,34));
        submitBtn.setPreferredSize(new Dimension(280,50));
        buttonPanel.add(submitBtn);
        
        MyButton fermerBtn = new MyButton("Fermer", new Color(255, 255, 255), new Color(44, 103, 242));
        fermerBtn.setFont(new  Font("sansserif",0,34));
        fermerBtn.setPreferredSize(new Dimension(180,50));
        fermerBtn.addActionListener(l->{
            System.exit(0);
        });
        buttonPanel.add(fermerBtn);
        buttonPanel.setOpaque(false);
        login.add(buttonPanel);
    }
    public MyButton getAuthBtn(){
        return submitBtn;
    }
    class MyLbl extends JLabel{
        MyLbl(String text, int taille, int bold){
            setText(text);
            setFont(new Font("sansserif",bold,taille));
            setForeground(Color.decode("#2c67f2"));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();

        login.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayer(login, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel login;
    // End of variables declaration//GEN-END:variables
}
